name = "libvorbis_jll"
uuid = "f27f6e37-5d2b-51aa-960f-b287f2bc3b7a"
version = "1.3.6+0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Ogg_jll = "e7412a2a-1a6e-54c0-be00-318e2571c051"

[compat]
julia = "1.3"
